### PR TITLE
jmoses/validate examples but dirty

### PR DESCRIPTION
**Pull request by jmoses**
- wip: test-examples single item check
- wip: make file targets
- wip: Jenkinsfile

### CODE REVIEW

**Comment by jmoses** [comment]
I just marked all of y'all that github recommended (aside from tom, I marked him to be annoying)

**Comment by jmoses** [comment]
I realize this is a quick and dirty validation step in CI, but that was 100% the intention at this time.

**Review by biblicalph — APPROVED** [review]
Oh my. 
I definitely shit the bed a lot writing documentation.
Thanks for adding this @jmoses

**Comment by jmoses** [comment]
🤣 Most of it was just adding a variable definition at least.

**Pull request merged**
